### ISSUE TITLE
Get up to date to mde/ejs

### ISSUE THREAD

**Issue by TimothyGu** [TimothyGu/ejs#1]
This is meant to be a rewrite of mde/ejs which is itself a rewrite of tj/ejs. The main reason for this fork is that ejs v2 is cool, but TOO SLOW. Yes, too SLOW. Therefore this repo is meant to be very performance-centric.
## Why is EJS v2 so slow?

I don't know, but preliminary profiling shows that the (over)use of regex is the main reason. tj/ejs uses an index and `indexOf()` which is extremely fast.
## TODO
- [x] Merge git metadata
- [x] Fix README
- [x] Port `include()`
- [x] Add tests from mde/ejs
- [x] Port delimiter option
- [x] Port locals -> opts shim
- [x] Port my caching algo in mde/ejs
- [x] Geddy style
